#postgres(DB)를 실행하는 로직
#1. db 라는 서비스 이름
#2. image : postgres:latest  -> 도커허브라는 곳에서 postgres 사용을 위한 이미지를 가져온다.
#3. container_name : postgres -> 이미지를 이용해서 컨테이너를 실행한다 이름은 postgres
#4  restart : always -> 컨테이너가 꺼지면 다시 켜준다.
#5  port는 post의 기본포트로 [5432] -> 실제 로컬 포트,    [: 5432] -> 컨테이너 속 포트
#6  environment: 환경변수를 준다. 아이디와 비밀번호는 .env파일에 넣어준다. 유출되지않기위해
#7  vloume : postgres 데이터들이 어디에 저장되는지 -> ./data:
#실제로 postgres를 로컬에 설치하고 사용하는게 아닌 도커를 이용해서 사용한다. 
#/var/lib/postgresql/data -> 로컬에다 설치하면 이 경로에 있는 데이터를 postgres에서 사용한다.
#이게 도커칸테이너 안에들어가니까 ./data: 이걸 이용해서 /var/lib/postgresql/data에 있는 data를 참조하게된다.
#vloume을 하는 이유는 도커컨테이너가 없어지면 데이터가 다없어지게된다. 하지만 volume으로 데이터폴더(./data:)를 로컬에다 두면 컨테이너를 없애도 데이터(./data:)를 보존할 수 있다.
#도커 컨테이너 실행 : 터미널에서 docker-compose up
#실행하고나면 data 폴더가 생기는데 실제 DB관한 데이터들이 들어가게 된다.
version : "3"
services:
  db:
    image: postgres:latest
    container_name : postgres
    restart : always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : "${DB_USER_ID}"
      POSTGRES_PASSWORD : "${DB_USER_PASSWORD}"
    volumes:
      - ./data:/var/lib/postgresql/data
